[package]
name = "autopp_inc_cli"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
description = "example package"

[dependencies]
autopp_inc = { path = "../autopp_inc" }
clap = { version = "4.4.1", features = ["derive"] }

[[bin]]
name = "autopp-inc"
path = "src/main.rs"
